import { Menu, Phone, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, NavLink } from 'react-router-dom'

export default function Navbar() {
  const [open, setOpen] = useState(false)
  const [scrolled, setScrolled] = useState(false)
  const links = [['Home', '/'], ['Services', '/services'], ['About', '/about'], ['Emergency Plumbing', '/emergency-plumber'], ['Contact', '/contact']]
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 8); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll) }, [])
  const closeMenu = () => setOpen(false)
  return <header className={`relative sticky top-0 z-50 border-b border-line bg-white/95 backdrop-blur transition-shadow duration-300 ${scrolled ? 'shadow-md shadow-ink/10' : ''}`}><div className="mx-auto flex min-h-[76px] max-w-7xl items-center justify-between gap-4 px-5 md:px-8"><Link to="/" className="font-display text-[1.15rem] font-bold leading-tight tracking-tight text-ink sm:text-xl" onClick={closeMenu}>USA Plumbing Service<span className="text-copper">.</span></Link><nav className="hidden items-center gap-6 lg:flex" aria-label="Primary navigation">{links.map(([name, path]) => <NavLink key={path} to={path} className={({ isActive }) => `whitespace-nowrap text-[13px] font-semibold transition-colors ${isActive ? 'text-copper' : 'text-muted hover:text-ink'}`}>{name}</NavLink>)}<a href="tel:9096230033" className="inline-flex items-center gap-2 bg-copper px-4 py-2.5 text-sm font-bold text-white transition hover:bg-copper-dark focus:outline-none focus:ring-2 focus:ring-copper focus:ring-offset-2"><Phone size={15} aria-hidden="true" /> Call Now</a></nav><div className="flex items-center gap-2 lg:hidden"><a href="tel:9096230033" className="inline-flex items-center gap-2 border border-copper px-3 py-2 text-xs font-bold text-copper" aria-label="Call USA Plumbing Service at 909-623-0033"><Phone size={15} aria-hidden="true" /> Call</a><button className="p-2 text-ink focus:outline-none focus:ring-2 focus:ring-copper" onClick={() => setOpen(!open)} aria-expanded={open} aria-controls="mobile-navigation" aria-label={open ? 'Close navigation menu' : 'Open navigation menu'}>{open ? <X /> : <Menu />}</button></div></div><div className={`absolute left-0 right-0 top-full overflow-hidden border-b border-line bg-white shadow-lg shadow-ink/10 transition-[max-height,opacity] duration-300 lg:hidden ${open ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'}`}><nav id="mobile-navigation" className="px-5 py-3 md:px-8" aria-label="Mobile navigation">{links.map(([name, path]) => <NavLink key={path} to={path} onClick={closeMenu} className={({ isActive }) => `block border-b border-line py-3.5 text-sm font-semibold ${isActive ? 'text-copper' : 'text-ink'}`}>{name}</NavLink>)}</nav></div></header>
}