import { Edit3, Eye, KeyRound, X } from 'lucide-react'
import { useState } from 'react'

function date(value) { return value ? new Date(value).toLocaleString() : 'Not available' }

export default function AdminManagement({ administrators, onRefresh, request, setMessage }) {
  const [modal, setModal] = useState(null)
  const [form, setForm] = useState({ email: '', newPassword: '', confirmPassword: '' })
  const [saving, setSaving] = useState(false)
  const open = (type, administrator) => { setForm({ email: administrator.email, newPassword: '', confirmPassword: '' }); setModal({ type, administrator }) }
  const close = () => setModal(null)
  const saveEdit = async (event) => { event.preventDefault(); setSaving(true); try { await request(`/api/admin/administrators/${modal.administrator.id}`, { method: 'PATCH', body: JSON.stringify({ email: form.email }) }); setMessage('Administrator updated.'); close(); await onRefresh() } catch (error) { setMessage(error.message === 'Invalid request' ? 'Enter a valid email address.' : 'Unable to update administrator.') } finally { setSaving(false) } }
  const savePassword = async (event) => { event.preventDefault(); if (form.newPassword !== form.confirmPassword) { setMessage('Passwords do not match.'); return } setSaving(true); try { await request(`/api/admin/administrators/${modal.administrator.id}/password`, { method: 'PATCH', body: JSON.stringify({ newPassword: form.newPassword }) }); setMessage('Administrator password changed.'); close() } catch (error) { setMessage(error.message === 'Invalid request' ? 'Password must be at least 12 characters.' : 'Unable to change administrator password.') } finally { setSaving(false) } }
  const toggleStatus = async (administrator) => { const active = !administrator.active; if (!active && !window.confirm(`Deactivate ${administrator.email}?`)) return; try { await request(`/api/admin/administrators/${administrator.id}/status`, { method: 'PATCH', body: JSON.stringify({ active }) }); setMessage(`Administrator ${active ? 'activated' : 'deactivated'}.`); await onRefresh() } catch (error) { setMessage(error.message || 'Unable to update administrator status.') } }
  const remove = async (administrator) => { if (!window.confirm(`Delete administrator ${administrator.email}? This cannot be undone.`)) return; try { await request(`/api/admin/administrators/${administrator.id}`, { method: 'DELETE' }); setMessage('Administrator deleted.'); await onRefresh() } catch (error) { setMessage(error.message || 'Unable to delete administrator.') } }
  return <section id="administrators" className="mt-12"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-copper">Access control</p><h2 className="mt-2 font-display text-3xl font-semibold">Administrators</h2></div><div className="mt-5 overflow-x-auto border border-line bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-line bg-sand text-xs uppercase tracking-wide text-muted"><tr>{['ID', 'Email', 'Status', 'Created', 'Actions'].map((heading) => <th key={heading} className="px-4 py-4">{heading}</th>)}</tr></thead><tbody className="divide-y divide-line">{administrators.map((administrator) => <tr key={administrator.id}><td className="px-4 py-4 text-muted">#{administrator.id}</td><td className="px-4 py-4 font-semibold">{administrator.email}</td><td className="px-4 py-4"><span className={administrator.active ? 'font-bold text-green-700' : 'font-bold text-muted'}>{administrator.active ? 'Active' : 'Inactive'}</span></td><td className="px-4 py-4 text-muted">{date(administrator.created_at)}</td><td className="px-4 py-4"><div className="flex flex-wrap gap-3"><button className="inline-flex items-center gap-1 font-bold text-copper" onClick={() => open('details', administrator)}><Eye size={15} />View Details</button><button className="inline-flex items-center gap-1 font-bold text-copper" onClick={() => open('edit', administrator)}><Edit3 size={15} />Edit</button><button className="inline-flex items-center gap-1 font-bold text-copper" onClick={() => open('password', administrator)}><KeyRound size={15} />Change Password</button><button className="text-xs font-bold text-ink" onClick={() => toggleStatus(administrator)}>{administrator.active ? 'Deactivate' : 'Activate'}</button><button className="text-xs font-bold text-red-700" disabled={administrators.length === 1} onClick={() => remove(administrator)}>Delete</button></div></td></tr>)}</tbody></table></div>{modal && <AdminModal modal={modal} form={form} setForm={setForm} saving={saving} close={close} saveEdit={saveEdit} savePassword={savePassword} />}</section>
}

function AdminModal({ modal, form, setForm, saving, close, saveEdit, savePassword }) { const administrator = modal.administrator; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-ink/50 p-5" role="dialog" aria-modal="true"><div className="w-full max-w-lg bg-white p-6 md:p-8"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-copper">Administrator</p><h3 className="mt-2 font-display text-2xl font-semibold">{modal.type === 'details' ? 'Details' : modal.type === 'edit' ? 'Edit Administrator' : 'Change Password'}</h3></div><button onClick={close} aria-label="Close administrator dialog"><X /></button></div>{modal.type === 'details' ? <div className="mt-6 grid gap-4 text-sm">{[['ID', administrator.id], ['Email', administrator.email], ['Status', administrator.active ? 'Active' : 'Inactive'], ['Created At', date(administrator.created_at)], ['Updated At', date(administrator.updated_at)]].map(([label, value]) => <div key={label}><p className="text-xs font-bold uppercase tracking-wide text-muted">{label}</p><p className="mt-1 font-semibold">{value}</p></div>)}</div> : <form className="mt-6 grid gap-4" onSubmit={modal.type === 'edit' ? saveEdit : savePassword}>{modal.type === 'edit' ? <><label className="grid gap-2 text-sm font-semibold">Email<input className="border border-line px-3 py-2 font-normal" type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} required /></label><button className="bg-copper px-4 py-3 text-sm font-bold text-white disabled:opacity-60" disabled={saving}>{saving ? 'Saving...' : 'Save changes'}</button></> : <><label className="grid gap-2 text-sm font-semibold">New Password<input className="border border-line px-3 py-2 font-normal" type="password" value={form.newPassword} onChange={(event) => setForm({ ...form, newPassword: event.target.value })} minLength="12" required /></label><label className="grid gap-2 text-sm font-semibold">Confirm New Password<input className="border border-line px-3 py-2 font-normal" type="password" value={form.confirmPassword} onChange={(event) => setForm({ ...form, confirmPassword: event.target.value })} minLength="12" required /></label><button className="bg-copper px-4 py-3 text-sm font-bold text-white disabled:opacity-60" disabled={saving}>{saving ? 'Saving...' : 'Change password'}</button></>}</form>}</div></div> }
